
gitadd:
	git add modules/*.js screens/*.js styles/*.js parts/*.js 
	git add smallparts/*.js bigparts/*.js styles/*.js libs/*.js 
	git add messenger/*.js
	git add index.ios.js index.android.js 
	git status

clean:
	rm -rf *.o *~
